### ISSUE TITLE
If date is marked, do not allow selection (date range)

### ISSUE THREAD

**Issue by MadMikeyB** [ManukMinasyan/vue-functional-calendar#1]
Hey @ManukMinasyan 

Just wondering if the above is possible at the moment or planned for a future release?

**Comment by MadMikeyB** [comment]
Maybe a new API method, `markDateImmutable`?

**Comment by ManukMinasyan** [comment]
It’s planned in the next release as well as ability with disabled dates. Thank you for your suggestion.

**Comment by ManukMinasyan** [comment]
Hello everyone. Thanks for your support. package updated to version 1.3.4.
