### ISSUE TITLE
updating markedDateRange prop values doesn't change the calendar

### ISSUE THREAD

**Issue by syldman** [ManukMinasyan/vue-functional-calendar#101]
I tried quite a bunch of ways:
- updating :calendar prop
- updating :config prop
- updating :value prop
- calling .updateCalendar()

and only re-rendering of the whole component worked

BTW: great job and thanks!

**Comment by Gamsake** [comment]
me neither (version: 2.8.88)

**Comment by didotsonev** [comment]
+1

**Comment by ngekoding** [comment]
I have a same issue when trying to update the configs, and successfully make it works by using vue watch cycle.

```vue
<!-- view -->
<functional-calendar
  ref="Calendar"
  v-model="calendar"
  :configs="calendarConfigs">
</functional-calendar>
```

Just manipulate the calendarConfigs value, e.g. change limits, etc...

And here is the main point to make it works.

```vue
watch: {
  calendarConfigs: {
    deep: true, 
    handler() {
      this.$refs.Calendar.setConfigs();
    }
  }
}
```

That's it. 

Hope can help anyone who have the same problem.

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
