### ISSUE TITLE
isMultiple + isDateRange + withTimePicker -> Start Date with Time + End Date with Time do not fit into layout

### ISSUE THREAD

**Issue by TitanFighter** [ManukMinasyan/vue-functional-calendar#104]
In addition to [this issue](https://github.com/Digital-Threads/vue-functional-calendar/issues/103) Start Date with Time + End Date with Time do not fit into layout.

![image](https://user-images.githubusercontent.com/12687911/89109051-70978980-d446-11ea-8937-8618fa75a41a.png)

**Comment by TitanFighter** [comment]
As I understand, this issue duplicates [this one](https://github.com/Digital-Threads/vue-functional-calendar/issues/49)

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
