### ISSUE TITLE
'marked_date' is not reactive

### ISSUE THREAD

**Issue by Gamsake** [ManukMinasyan/vue-functional-calendar#109]
me neither (version: 2.8.88)

someone says _'using :key solves the issue'_, but that makes other issues

_Originally posted by @Gamsake in https://github.com/Digital-Threads/vue-functional-calendar/issues/101#issuecomment-683683231_

**Comment by ngekoding** [comment]
You can try this one https://github.com/ManukMinasyan/vue-functional-calendar/issues/101#issuecomment-871354071

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
