### ISSUE TITLE
Date range multiple calendar with a Limit shows a full disabled month

### ISSUE THREAD

**Issue by mwleinad** [ManukMinasyan/vue-functional-calendar#114]
Here's my setup 
`<functional-calendar
     v-model="dateRangeComputed"
     is-dark
     :is-date-range='true'
     :is-multiple='true'
     :calendars-count='2'
     :limits="limits"
    ></functional-calendar>`

And I get this as a result
![image](https://user-images.githubusercontent.com/15146158/99286172-1b696300-27fe-11eb-822a-8df310053a13.png)

How can I limit the calendar to November, I don't want to show December as all the dates are disabled anyways.
Is this possible?

**Comment by mwleinad** [comment]
Any idea about this one?

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
