### ISSUE TITLE
disabledDates: ["beforeToday"] does not work with datePicker: true

### ISSUE THREAD

**Issue by lucapu88** [ManukMinasyan/vue-functional-calendar#115]
I gave these settings but if i select the date disabled, but it makes them select anyway!

     `calendarConfigs: {
             disabledDates: ["beforeToday"], //disabilita le date precedenti alla data odierna
             datePicker: true, //abilita la selezione singola
             isMarked: false,
        },`

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
