### ISSUE TITLE
disabledDates: ['beforeToday',  '24/12/2020', ...] does not work with is-date-range enabled

### ISSUE THREAD

**Issue by Etheliene** [ManukMinasyan/vue-functional-calendar#116]
If I set "is-date-range" to true the disabled dates are not disabled anymore.

**Comment by lucapu88** [comment]
I have a very similar problem, but apparently no one answers... if you can solve it can you tell me please?

**Comment by dwaynehulsman** [comment]
This should be sorted in 1d6f8da

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
