### ISSUE TITLE
Time is not shown in the input field even I specified the withTimePicker option in the config

### ISSUE THREAD

**Issue by marinelbare902** [ManukMinasyan/vue-functional-calendar#126]
@ManukMinasyan 
This is my configuration for the functional calendar but I am not able to see the time in the input field.

```
calendarConfigs: {
	isModal: true,
	isDatePicker: true,
	withTimePicker: true,
	isDark: true,
	placeholder: 'Date & Time'
}
```

The time is shown up in the time picker but not able to see in the input field.
Could you let me know what the problem is?

![image](https://user-images.githubusercontent.com/68440634/109719581-b55edc80-7b5d-11eb-8c2c-45b270d4c446.png)

**Comment by miracle-arrow** [comment]
The same issue here.

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
