### ISSUE TITLE
Problem with legacy browsers

### ISSUE THREAD

**Issue by rangermeier** [ManukMinasyan/vue-functional-calendar#13]
When I use your component in my app, it doesn't load in browsers that don't support ES6 (i.e. IE 11) because babel is configured not to process anything from from _node_modules_.

Could you please provide an ES5 dist version of your component?

I assume it's quite common to not process _node_modules_ so probably more users will face this issue.

**Comment by Chuiantw1212** [comment]
I could be the best calendar component I have ever seen. What a shame.
