### ISSUE TITLE
Invalid prop: type check failed for prop "value". Expected Object, got String with value ""

### ISSUE THREAD

**Issue by Taylorchong123** [ManukMinasyan/vue-functional-calendar#132]
don't know what problem

  <FunctionalCalendar 
                                v-model='editDate'
                                :hidden-elements="['leftAndRightDays']"
                                :is-date-picker="true"
                               
                                                          
                                >
                                
                                </FunctionalCalendar>

**Comment by TitanFighter** [comment]
Show the value of `editDate`

**Comment by Taylorchong123** [comment]
> Show the value of `editDate`

![image](https://user-images.githubusercontent.com/51316287/117744709-c9991700-b23b-11eb-9f0f-d91474b288eb.png)
