### ISSUE TITLE
Event not working when using CDN!

### ISSUE THREAD

**Issue by ngekoding** [ManukMinasyan/vue-functional-calendar#134]
Hi, thanks for this awesome works.

I just trying to listen for month changes as the given example, but the event not firing when using cdn version.

Here is the test: https://codesandbox.io/s/vue-functional-calendar-event-problem-wwohu?file=/index.html

Anyone know to solve this problem?

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
