### ISSUE TITLE
Import styles manually

### ISSUE THREAD

**Issue by kukudim** [ManukMinasyan/vue-functional-calendar#136]
Is it possible to remove the import `calendar.scss` from the component so that I can import it manually and override the scss-variables? Thanks in advance.

**Comment by rhysmatthew** [comment]
I second this. Unfortunately unable to use this plugin as I'm not handling my CSS in this way.

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
