### ISSUE TITLE
newCurrentDate property does not work

### ISSUE THREAD

**Issue by Sovai** [ManukMinasyan/vue-functional-calendar#139]
hi, I need to set current-day of my calendar to a fixed timezone date and the newCurrentDate property doesn't work as it is supposed to.

here is my code example

```
 <functional-calendar
                  ref="selectDate"
                  v-model="calendarData"
                  :is-date-picker="true"
                  date-format="mm/dd/yyyy"
                  :limits="limits"
                  :new-current-date="new Date(2021, 10, 11)" // doesn't work
                  @choseDay="handleClickDay"
                ></functional-calendar>
```

**Comment by Monomachus** [comment]
I think that one should be

`:newCurrentDate 
`

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
