### ISSUE TITLE
Suggestions: Let's make the calendar better :)

### ISSUE THREAD

**Issue by ManukMinasyan** [ManukMinasyan/vue-functional-calendar#14]
Please write your suggestions here.
Thanks.

**Comment by camilleb** [comment]
Could be nice if there was the possibility to select multiple non continuous dates 🙂

**Comment by ManukMinasyan** [comment]
@camilleb prop "marked-dates" you are lacking?

**Comment by camilleb** [comment]
@ManukMinasyan it works when you already know the dates, but user can't select multiple date by clicking on the calendar. It could also be solved by adding a "clickedDay" event.

**Comment by ManukMinasyan** [comment]
@camilleb thank you for your suggestion. Now everything is clear. I will do that)

**Comment by 13thbit** [comment]
Optionally display Week Numbers would be great!

**Comment by ManukMinasyan** [comment]
> Optionally display Week Numbers
Sure )
https://github.com/ManukMinasyan/vue-functional-calendar/projects/1#card-20648892

**Comment by RicLeP** [comment]
Being able to select time too. So hard to find good datetime pickers.

**Comment by ManukMinasyan** [comment]
> Being able to select time too. So hard to find good datetime pickers.

Sure) Thank you for you suggestion.
https://github.com/ManukMinasyan/vue-functional-calendar/projects/1#card-21892094

**Comment by stuta** [comment]
With multiple calendars and date range picker you should change only one side when changing month so that you can see the other end of selection. If months are not continuous there should be visual sign in the middle of calendars.

**Comment by stuta** [comment]
Configurable shortcuts like 'This week', 'Last week', 'Last month'.

**Comment by atilacamurca** [comment]
About localization (l10n), I understand that this library allows to pass `dayNames` and `monthNames` as a way change the locale. My concern is about avoid repeating this process. So, one suggestion is to allow to pass these props while install vue-functional-calendar, for example:

```js
GlobalVue.use(plugin, options: {
  dayNames: [],
  monthNames: []
});
```

What do you think?

**Comment by ManukMinasyan** [comment]
> About localization (l10n), I understand that this library allows to pass `dayNames` and `monthNames` as a way change the locale. My concern is about avoid repeating this process. So, one suggestion is to allow to pass these props while install vue-functional-calendar, for example:
> 
> ```js
> GlobalVue.use(plugin, options: {
>   dayNames: [/* ... */],
>   monthNames: [/* ... */]
> });
> ```
> 
> What do you think?

This is a good idea, in the next versions I will definitely do it.

**Comment by adamorlowskipoland** [comment]
How about making a named slot (let say under a day number) for additional info, icon etc.?

**Comment by ManukMinasyan** [comment]
> How about making a named slot (let say under a day number) for additional info, icon etc.?

I plan to do this on the next versions. ) 
Thank you.

**Comment by stuta** [comment]
> > Optionally display Week Numbers
> 
> Sure )
> https://github.com/ManukMinasyan/vue-functional-calendar/projects/1#card-20648892

How can I enable week numbers?

**Comment by masterix21** [comment]
Hi dear,

what do you think about the custom inputs (slot) using modal version?

**Comment by Uninen** [comment]
First, this component looks really nice, Thank You for your work!

I'd like to suggest better themability, either by exposing few color variables (to easily be able to create for example themes or dark mode etc) or at least documenting what would be the best way to do it.

**Comment by ManukMinasyan** [comment]
Hello dears,
Thank you for your message, I planned to do it all on the next week, thanks :)

**Comment by ManukMinasyan** [comment]
Hello dear developers,
Already completed slots functionality.
You can use the "week" and "day" props.

Thank you again for your support. ❤️

**Comment by Adizbek** [comment]
Add @onDateSelected event

**Comment by jamesleonardleonard** [comment]
I can't work out how to set the inital date when using as a datepicker - could you explain how to do this please?

**Comment by jamesleonardleonard** [comment]
have set the dateFormat to dd-mm-yyyy but the datepicker still displays 9/8/2019 when you select a date - can/does the format affect how the date is displayed?

**Comment by jaywilburn** [comment]
auto-apply and auto-close would be nice

**Comment by ManukMinasyan** [comment]
> I can't work out how to set the inital date when using as a datepicker - could you explain how to do this please?

If you need set start calendar date. You need use "newCurrentDate" prop.

**Comment by ManukMinasyan** [comment]
> dd-mm-yyyy

Please look at this example.
[https://codesandbox.io/s/980jov4m4p?fontsize=14&hidenavigation=1](https://codesandbox.io/s/980jov4m4p?fontsize=14&hidenavigation=1)

**Comment by ManukMinasyan** [comment]
> auto-apply and auto-close would be nice

What do you mean about auto-apply and auto-close?  What to do these functions and when?

Thanks.

**Comment by jaywilburn** [comment]
Once you’ve selected the date range, allowing the calendar element to auto close, hiding it. I’m sure I can probably auto apply it from the model itself.

**Comment by jaywilburn** [comment]
Is a single date select in date-range mode possible? I can see good use for that too.

**Comment by ManukMinasyan** [comment]
@jaywilburn please look at this example. Did you want it?
[https://codesandbox.io/s/vuejs-functional-calendar-k1h1c](https://codesandbox.io/s/vuejs-functional-calendar-k1h1c)

**Comment by jamesleonardleonard** [comment]
> > dd-mm-yyyy
> 
> Please look at this example.
> https://codesandbox.io/s/980jov4m4p?fontsize=14&hidenavigation=1

Thanks Manuk, I had a look at that, when I click the Change Date button the calendar goes blank - all days disappear.

What I wanted was a modal datepicker that shows the date in dd-mm-yyyy format - is there a way to do that please?

**Comment by jaywilburn** [comment]
> @jaywilburn please look at this example. Did you want it?
> https://codesandbox.io/s/vuejs-functional-calendar-k1h1c

Yes, thanks!

**Comment by ManukMinasyan** [comment]
@jamesleonardleonard you need pass date argument like on the date format.
Example:

`:date-format="'mm-yyyy-dd'"
chooseDate('08-2019-05');`

`:date-format="'yyyy/mm/dd'"
chooseDate('2019/08/05');`

**Comment by oghea** [comment]
Hello Manuk,

I try to using props disableDate but its not working, but if im trying to use disabledDayNames its working. 

then if i want to use @click in slot or using styles :hover for class its not working too.

Thanks u

**Comment by ManukMinasyan** [comment]
Hey dear @oghea , please check this example. Thanks.
https://codesandbox.io/s/vuejs-functional-calendar-component-t9nlf

**Comment by garf** [comment]
Is it possible to preset date with v-model? I can't make it work

**Comment by ManukMinasyan** [comment]
Hey @garf . 
Now you can set the date using ChooseDate method only.
You can add this code to your mounted or created method. And it will work.

` this.$refs.Calendar.ChooseDate('2018-12-12');`

Thanks.

**Comment by garf** [comment]
@ManukMinasyan But it's not a date range, right?

**Comment by ManukMinasyan** [comment]
@garf, yes, if you need to set the date range, you need to use the markedDateRange prop.

**Comment by xlcrr** [comment]
Just wanted to say thanks!

**Comment by garf** [comment]
Currently it's not possible to select in a date range a single date. I think it should be allowed, as sometimes you want to select only one day range.

**Comment by garf** [comment]
https://github.com/ManukMinasyan/vue-functional-calendar/pull/33
Here we go :)

**Comment by ManukMinasyan** [comment]
Thank you @garf  :)

**Comment by HaileyGermanotta** [comment]
Hello Manuk, I try to use props 'markedDates' to display specific dates manually when I switch month page, however, I can not see any mark on these dates. Could you please help me out?

For example, I reset the markedDates array when I jump to October page from November
`:marked-dates="markedDates"`

`this.markedDates = [{ date: '1/10/2019', class: 'marked-class' }, { date: '12/10/2019', class: 'marked-class' }]`

**Comment by ManukMinasyan** [comment]
Hi @HaileyGermanotta . Please share your code.

**Comment by HaileyGermanotta** [comment]
`      <FunctionalCalendar
        :date-format="'dd/mm/yyyy'"
        :marked-dates="markedDates"
        @changedMonth="changeMonth">
      </FunctionalCalendar>
`

`import { FunctionalCalendar } from 'vue-functional-calendar'
export default {
  components: {
    FunctionalCalendar
  },
  data() {
    return {
          markedDates: [],
    }
  },
  methods: {
     changeMonth(date) {
       // ..... retrive an array of dates from the server and set to markedDates
       this.markedDates = ['1/11/2019', '2/11/2019']
     }
   }
}
`

but no marks on the calendar, did I miss anything? Thank you!

**Comment by ManukMinasyan** [comment]
@HaileyGermanotta you need to use the computed property for reactive props.

**Comment by ManukMinasyan** [comment]
Example:
```html
<FunctionalCalendar
    :date-format="'dd/mm/yyyy'"
    :marked-dates="reactiveMarkedDates"
    @changedMonth="changeMonth">
</FunctionalCalendar>
```

```JavaScript
import { FunctionalCalendar } from 'vue-functional-calendar'
export default {
  components: {
    FunctionalCalendar
  },
  data() {
    return {
        markedDates: [],
    }
  },
computed: {
reactiveMarkedDates() {
return this.markedDates;
}
}
  methods: {
     changeMonth(date) {
       // ..... retrieve an array of dates from the server and set to markedDates
       this.markedDates = ['1/11/2019', '2/11/2019']
     }
   }
}
```

**Comment by jfustier-it** [comment]
Hey !

When using the range mode it would be cool to be able to disable range date, like :

{ start: '13-10-2019', end: '15-10-2019' }
Thx :)

**Comment by ManukMinasyan** [comment]
@jfustier-it  thank you for your suggestion. Now everything is clear. I will do that)

**Comment by ManukMinasyan** [comment]
@jfustier-it thank you for your suggestion. I will do that)

**Comment by ignasga** [comment]
> First, this component looks really nice, Thank You for your work!
> 
> I'd like to suggest better themability, either by exposing few color variables (to easily be able to create for example themes or dark mode etc) or at least documenting what would be the best way to do it.
This would definitely be useful.
But until it's implemented, how can we change what colour selected day and current (today) day has? I'm thinking about uverriding some CSS classed, but which should I override exactly?

**Comment by ManukMinasyan** [comment]
> > First, this component looks really nice, Thank You for your work!
> > I'd like to suggest better themability, either by exposing few color variables (to easily be able to create for example themes or dark mode etc) or at least documenting what would be the best way to do it.
> 
> This would definitely be useful.
> But until it's implemented, how can we change what colour selected day and current (today) day has? I'm thinking about uverriding some CSS classed, but which should I override exactly?

We have a variables.scss file, you can see this file. And overwrite colors. Thanks

**Comment by Seaclick** [comment]
Hello @ManukMinasyan 

Thanks for your work, it's awesome.
It would be great if calendars were stacked when using "isMultiple" and "calendarsCount="x" on mobile advices (responsive).

What do you think about it?

**Comment by xlcrr** [comment]
Is it possible to change time picker from 24 hour, to 12-hour am/pm format?

**Comment by Seaclick** [comment]
Hello @ManukMinasyan 

I think it should be nice to have a prop for disable dates before the current date.

Thnaks for your answers.

**Comment by xlcrr** [comment]
Also, it would be nice to have the option to include timezone

**Comment by denys-vladymyrov** [comment]
Hello @ManukMinasyan 

Thank you so much for your calendar! 

And can you tell please, how to to show "Week Number" in calendar? As i understood you have implemented it already: https://github.com/ManukMinasyan/vue-functional-calendar/projects/1#card-20648892 but don't know how to enable it.

Thank you in advance.

**Comment by ManukMinasyan** [comment]
> Hello @ManukMinasyan
> 
> Thanks for your work, it's awesome.
> It would be nice if calendars were stacked when using "isMultiple" and "calendarsCount="x" on mobile advices (responsive). What do you think about it?
> 
> Also i've just install your package so I use the last version and it's still not possible to select only one date when using dateRange.
> 
> Thanks for your answers.

Hey @Seaclick . For this I created card https://github.com/ManukMinasyan/vue-functional-calendar/projects/1#card-30587783 . 
For date range, please see this code https://y3jnxov469.codesandbox.io/ . Works correctly.

**Comment by ManukMinasyan** [comment]
> Hello @ManukMinasyan
> 
> I think it should be nice to have a prop for disable dates before the current date.
> 
> Thnaks for your answers.

We already have this functionality, thanks.

https://github.com/ManukMinasyan/vue-functional-calendar/commit/57dc30ef56f5ed026c7207a72ab2b7ccd8a8a513

**Comment by ManukMinasyan** [comment]
> Also, it would be nice to have the option to include timezone

I plan to do it. Thanks.
https://github.com/ManukMinasyan/vue-functional-calendar/projects/1#card-30587837

**Comment by ManukMinasyan** [comment]
> Hello @ManukMinasyan
> 
> Thank you so much for your calendar!
> 
> And can you tell please, how to to show "Week Number" in calendar? As i understood you have implemented it already: https://github.com/ManukMinasyan/vue-functional-calendar/projects/1#card-20648892 but don't know how to enable it.
> 
> Thank you in advance.

Hey @denys-vladymyrov . We already have a "showWeekNumbers" prop for this. Thanks

**Comment by denys-vladymyrov** [comment]
> Hey @denys-vladymyrov . We already have a "showWeekNumbers" prop for this. Thanks

Hi @ManukMinasyan . I've tried in as a prop - :showWeekNumbers="true"  and tried as an object - 
       Vue.use(FunctionalCalendar, {
          showWeekNumbers: "true"
       }); 

but it doesn't show week numbers :(

**Comment by Seaclick** [comment]
@ManukMinasyan Thanks for your answers.

**Comment by Seaclick** [comment]
> > Hello @ManukMinasyan
> > I think it should be nice to have a prop for disable dates before the current date.
> > Thnaks for your answers.
> 
> We already have this functionality, thanks.
> 
> [57dc30e](https://github.com/ManukMinasyan/vue-functional-calendar/commit/57dc30ef56f5ed026c7207a72ab2b7ccd8a8a513)

Hello @ManukMinasyan 

Thanks for this feature. I've tried this code but it sounds that is not working.

I've trid this:
`data: () => ({
			SearchDateStore,
			
			checkin: null,
			checkout: null,
			today: moment().startOf('day'),
			
			selectedDateRange: {},
			configs: {
				isDateRange: true,
				dayNames: ['lun', 'mar', 'mer', 'jeu', 'ven', 'sam', 'dim'],
				monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
				shortMonthNames: ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Juin', 'Juil', 'Aou', 'Sep', 'Oct', 'Nov', 'Dec'],
				placeholder: 'jj/mm/aaaa',
				dateFormat: 'dd/mm/yyyy',
				disabledDates: ['beforeToday']
			},
		}),`

And like this:

`:disabled-dates="['beforeToday']"`

Nothing happened, the dates are still enabled.

**Comment by ManukMinasyan** [comment]
@Seaclick https://codesandbox.io/s/vuejs-functional-calendar-component-x4p7h?fontsize=14&hidenavigation=1&theme=dark please take a look.

**Comment by ManukMinasyan** [comment]
@denys-vladymyrov https://codesandbox.io/s/vuejs-functional-calendar-component-u7748?fontsize=14&hidenavigation=1&theme=dark please take a look.

**Comment by Seaclick** [comment]
> @Seaclick https://codesandbox.io/s/vuejs-functional-calendar-component-x4p7h?fontsize=14&hidenavigation=1&theme=dark please take a look.

Hello @ManukMinasyan 

Thanks a lot for your answer and your time.
There is no diff between your sandbox and my code, so i have update the package to the 2.7.1 version. It still not working.
Maybe it is due to my specific case, the calendar is in a modal... Anyway...

Thanks a lots for your work and your time. I wish you a very happy festive season.

**Comment by denys-vladymyrov** [comment]
> @denys-vladymyrov https://codesandbox.io/s/vuejs-functional-calendar-component-u7748?fontsize=14&hidenavigation=1&theme=dark please take a look.

@ManukMinasyan Yes, thank you, the issue was in my old version 2.6.7. I updated to 2.69 and it worked. But i wanted i bit another feature, actually :) 
    So that weeks are displayed on the left side of the calendar and they would be counted from the beginning of the year. 
    For example if i choose February and on the left side of calendar there will be weeks number like first week of February is 5, second is 6 and so on. In this case, for example, in summer i can understand which week is no (30 or 35 etc).

Like on this screen:
https://www.google.com/search?q=web+calendar+with+week+numbers+example&rlz=1C1SQJL_enUA876UA876&sxsrf=ACYBGNSMujsdnuJA08x7byFBffUgCASnoQ:1576773633597&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj5-sjCk8LmAhWswAIHHTpnAvIQ_AUoAXoECAsQAw&biw=2048&bih=1019#imgrc=fbxjiU_p80KjnM:

If it is possible to add it in the future I would really appreciate it

**Comment by Seaclick** [comment]
> @Seaclick https://codesandbox.io/s/vuejs-functional-calendar-component-x4p7h?fontsize=14&hidenavigation=1&theme=dark please take a look.

Thanks a lot.

**Comment by Adizbek** [comment]
Working with dates very awful, as they not incompatible with other formats, why do you use 1/1/2020 instead of 01/01/2020 ? Many times I have spent plenty time to find out this problem.

**Comment by Uninen** [comment]
This styled with Tailwind CSS would be awesome 🎉

**Comment by daaner** [comment]
> > Hello @ManukMinasyan
> > Thanks for your work, it's awesome.
> > It would be nice if calendars were stacked when using "isMultiple" and "calendarsCount="x" on mobile advices (responsive). What do you think about it?
> > Also i've just install your package so I use the last version and it's still not possible to select only one date when using dateRange.
> > Thanks for your answers.
> 
> Hey @Seaclick . For this I created card https://github.com/ManukMinasyan/vue-functional-calendar/projects/1#card-30587783 .
> For date range, please see this code https://y3jnxov469.codesandbox.io/ . Works correctly.

not working as it should. In general, there is no reactivity. I already went through almost all the options, all the same, when changing data from the array, the data is not redrawn. Very sad
The problem is observed in markedDates and disabledDates
By the method, I try to drop the whole array and substitute a new one and still nothing

**Comment by daaner** [comment]
> ```
> <FunctionalCalendar
>     :date-format="'dd/mm/yyyy'"
>     :marked-dates="markedDates"
>     @changedMonth="changeMonth">
> </FunctionalCalendar>
> ```
> 
> ```js
> import { FunctionalCalendar } from 'vue-functional-calendar'
> export default {
>   components: {
>     FunctionalCalendar
>   },
>   data() {
>     return {
>         markedDates: [],
>     }
>   },
>   methods: {
>      changeMonth(date) {
>        // ..... retrieve an array of dates from the server and set to markedDates
>        this.markedDates = ['1/11/2019', '2/11/2019']
>      }
>    }
> }
> ```
> 
> but no marks on the calendar. Did I miss anything? Thank you!

not working as it should. In general, there is no reactivity. I already went through almost all the options, all the same, when changing data from the array, the data is not redrawn. Very sad
The problem is observed in markedDates and disabledDates
By the method, I try to drop the whole array and substitute a new one and still nothing

**Comment by KingWarin** [comment]
Would be great if isAutoCloseable would also work on the times. Also ran into problems with date-time-picker when in modal-mode, but maybe I'll be opening a seperate issue for this.

**Comment by stuta** [comment]
Has anyone got week numbers to show?

**Comment by ManukMinasyan** [comment]
> > ```
> > <FunctionalCalendar
> >     :date-format="'dd/mm/yyyy'"
> >     :marked-dates="markedDates"
> >     @changedMonth="changeMonth">
> > </FunctionalCalendar>
> > ```
> > 
> > 
> > ```js
> > import { FunctionalCalendar } from 'vue-functional-calendar'
> > export default {
> >   components: {
> >     FunctionalCalendar
> >   },
> >   data() {
> >     return {
> >         markedDates: [],
> >     }
> >   },
> >   methods: {
> >      changeMonth(date) {
> >        // ..... retrieve an array of dates from the server and set to markedDates
> >        this.markedDates = ['1/11/2019', '2/11/2019']
> >      }
> >    }
> > }
> > ```
> > 
> > 
> > but no marks on the calendar. Did I miss anything? Thank you!
> 
> not working as it should. In general, there is no reactivity. I already went through almost all the options, all the same, when changing data from the array, the data is not redrawn. Very sad
> The problem is observed in markedDates and disabledDates
> By the method, I try to drop the whole array and substitute a new one and still nothing

Thanks for your feedback, this problem is solved in the latest version.

**Comment by ManukMinasyan** [comment]
> Has anyone got week numbers to show?

This problem is solved in the 2.8.1 version.
You can make it work with prop showWeekNumbers.
Thank you, for your feedback,

**Comment by asideHazle** [comment]
Can I use Timepicker only or how about add is-date-picker props? 
After pick date and time, if wanna change time only, have to pick date first again.

**Comment by xlcrr** [comment]
It is possible to edit the header? We would like to close TimePicker with an arrow on the left instead of X on the right. Would be nice instead of having to fork the package ;-)

**Comment by sp0ken** [comment]
It would great to have another props opposite of `disabledDates` (`enabledDates` for example) where dates not in this array would be disabled in the calendar.

**Comment by denys-vladymyrov** [comment]
@ManukMinasyan  Thanks a lot for showWeekNumbers!!!

**Comment by wushan** [comment]
1. Nice to have a default selection object to let the component have a default range. I know there is a `markedRange` but I think is totally different.
ex: 
```
calendarData: {
        dateRange: {
          end: {
            date: '2020-2-28'
          },
          start: {
            date: '2020-3-5'
          }
        }
      }
```

2. I am using `@close` event on data change, but this is meant to fire after modal close, I think we should have an exactly `@change` event for the values.

3. A formatter option for output data and simplify the result. ex:
```
calendarData: {
  dataRange: ['15834749384', '15834749384'] // X
  dataRange: ['2020-03-05', '2020-04-10']
}
```

**Comment by Batsirai** [comment]
Be great to have Time Minute intervals: 5,15, 20, 30 mins

**Comment by itpropro** [comment]
I just started using functional-calendar and it is the most performant and smallest solution for vue that I know.
To be able to achieve what I am doing in some other projects with e.g. v-calendar, the following things would be good improvements:
1. Offer styling support. I am mainly using tailwindcss meaning everything is a more or less custom element. Not being able to style the whole calendar is a no go for production.
2. More modal settings. I miss some settings for modal positioning like top, left, top-start, top-center, etc..
3. Modal only mode. Be able to use your own input fields with functional-calendar as popover only.

Thanks for all the the work you have done already, it's time for a performant and modern solution for calendars in vue!
I also love the idea behind Treeware and will continue to support offset.earth with donations.

**Comment by hmaesta** [comment]
@itpropro I just did an implementation with Tailwind CSS and custom input (kind of). Maybe it can help you.

→ https://codesandbox.io/s/vue-functional-calendar-tailwind-04zcr?file=/src/App.vue

@ManukMinasyan Any way to improve the code above? And maybe replace the default CSS?

**Comment by kadrikaur** [comment]
Perhaps a way to set any day of the week as the first day? So instead of
`:sundayStart="true"` => `:firstDayOfWeek="2"`

**Comment by Etheliene** [comment]
Is there a way to check for disabled dates if user selected a date range? Let's say weekends are disabled, user selects 2 weeks (including the weekends). So daterange.start and end would be correct, but can I filter the disabled dates within that daterange?

**Comment by denys-vladymyrov** [comment]
Is it possible to run this nice calendar in VueJs3?

**Comment by pgodwood** [comment]
Woould be really cool to combine both, date range and date picker.
i.e. select a date rang of 10 days and then tick one date somewhere in the middle to unselect

**Comment by ManukMinasyan** [comment]
For discussions: https://github.com/ManukMinasyan/vue-functional-calendar/discussions/145
