### ISSUE TITLE
Slot option for isMultipleDatePicker type

### ISSUE THREAD

**Issue by timoteiNicsoft** [ManukMinasyan/vue-functional-calendar#141]
Hi
Can be add the slot option for isMultipleDatePicker type? For isDatePicker and isRangePicker exist, but for multiselect not. Thanks

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
