### ISSUE TITLE
disabledDayNames + sundayStart disables days one column to the right of expected

### ISSUE THREAD

**Issue by TitanFighter** [ManukMinasyan/vue-functional-calendar#148]
Easy replicable with the codesandbox demo - just add `sunday-start` and you will see that instead of Su + We calendar disables Mo and Th.

```
        <h4>Disabled Day Names</h4>
        <h5>...</h5>
        <functional-calendar
          class="calendar"
          :is-date-picker="true"
          :disabledDayNames="['Su', 'We']"
          sunday-start
        ></functional-calendar>
```

![image](https://user-images.githubusercontent.com/12687911/151080420-4176101c-b57b-4382-b5c3-78214ff34e23.png)

**Comment by ManukMinasyan** [comment]
@TitanFighter Now I don't have time. Thanks for your feedback. If you have free time, you can contribute. Thankls
