### ISSUE TITLE
4 small issues

### ISSUE THREAD

**Issue by tbyte80** [ManukMinasyan/vue-functional-calendar#15]
Hello,
thanks for your work! I have 4 small issues:

1. Even with `sunday-start="false"` the calendar is still starting with Su (only with default daynames. When dayNames option is provided it works.)
2. date format "dd.mm.yyyy" will display 1.1.2019 instead of 01.01.2019
3. in dateRange mode (modal active), modal is not closing if a date range is selected. Also, an extra click will reset the form. Another click will start a new range. This happens only in modal mode. in calendar mode behaviour is fine!
4. Can u add `user-select: none; ` to your styles? To prevent text selection when browsing through months.

**Comment by ManukMinasyan** [comment]
Hello @tbyte80 , thank you for your suggestions.
You have done the correct considerations.
I will complete them in the near feature.
Thanks.
