### ISSUE TITLE
disabledDates not working

### ISSUE THREAD

**Issue by joker506** [ManukMinasyan/vue-functional-calendar#153]
trying to set the disabledDates range: ["07/05/2022", "09/05/2022"], at the same time, this configuration does not work, but if I set disabledDates: ["afterToday"] or disabledDates: ["beforeToday"], then everything is ok

**Comment by Jairitos** [comment]
@joker506 You should enter the dates in the same format as you use for 'dateFormat'.

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
