### ISSUE TITLE
Multiple Calendars starting from the previous month?

### ISSUE THREAD

**Issue by rochabianca** [ManukMinasyan/vue-functional-calendar#156]
Hello and thank you for the great calendar library!

I would like to ask if there is a way to make multiple calendars starting from the previous month and  ending on the atual month?
For example, I'm on the month of October and so the calendars would start at September and end in October instead of starting on October and ending on November.

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
