### ISSUE TITLE
TypeError: this.$set is not a function

### ISSUE THREAD

**Issue by luca-giardina** [ManukMinasyan/vue-functional-calendar#159]
FunctionalCalendar.vue:502 Uncaught TypeError: this.$set is not a function
    at FunctionalCalendar.vue:502:18
    at Array.forEach (<anonymous>)
    
    
`this.$set(this.fConfigs, objectKey, this.configs[objectKey])`

    "devDependencies": {
        "@vitejs/plugin-vue": "^4.5.2",
        "axios": "^1.6.1",
        "laravel-vite-plugin": "^0.8.0",
        "sass": "^1.69.5",
        "vite": "^4.0.0",
        "vue-functional-calendar": "^2.9.98"
    },
    "dependencies": {
        "vue": "^3.2.36"
    }

**Comment by ManukMinasyan** [comment]
@luca-giardina thank you for report. Unfortunately the calendar does not work with Vue 3
