### ISSUE TITLE
Date range picker issue in Month of January

### ISSUE THREAD

**Issue by mihir0109** [ManukMinasyan/vue-functional-calendar#16]
Unable to choose  date range only for month of January of any year. can you please check the same?

**Comment by ManukMinasyan** [comment]
https://y3jnxov469.codesandbox.io/ - please check it, in this URL, and let me know if the bug exists.

**Comment by mihir0109** [comment]
In this URL it's working, but not in code.. same code taken from git repo...

**Comment by ManukMinasyan** [comment]
Have you updated the component latest version?

**Comment by mihir0109** [comment]
Can you tell me how to update it?
I am just using:
npm i vue-functional-calendar --save

**Comment by ManukMinasyan** [comment]
Please open the file package.json.
And for example 
"vue-functional-calendar": "2.0.0"
change to 
"vue-functional-calendar": "2.1.5".
After that run command "npm update"

**Comment by mihir0109** [comment]
It's already v 2.1.5 in package.json

**Comment by ManukMinasyan** [comment]
Please share the bug screen with me.

**Comment by mihir0109** [comment]
Sorry, have removed code and replaced with another library.
