### ISSUE TITLE
Hello need more classes

### ISSUE THREAD

**Issue by AndreyBrusnikin** [ManukMinasyan/vue-functional-calendar#17]
Hello, i used your calendar. Could you add two classes to calendar.
   if(day.date === this.calendar.dateRange.start ){
            classes.push('start-date');
    }
    if(day.date === this.calendar.dateRange.end ){
            classes.push('end-date');
    }

 I just really miss them.  
Thank you so much.

**Comment by ManukMinasyan** [comment]
Hello @AndreyBrusnikin .
I will add it for sure in the next version.
Thank you too for your review.

**Comment by ManukMinasyan** [comment]
I have already updated the component.
Please check the version vue-functional-calendar@2.1.7

:)

**Comment by AndreyBrusnikin** [comment]
thx)))))
