### ISSUE TITLE
select date accross moth style bug

### ISSUE THREAD

**Issue by iamstd** [ManukMinasyan/vue-functional-calendar#19]
hi，
   Manuk, thanks for your calendar, however, I find a bug when I have chosen my date range across the month, then I change my date range in the next month, the previous style is still here. can you fix it as soon as possible? thank you.
![1556505781947](https://user-images.githubusercontent.com/13133520/56874298-94ae3300-6a6b-11e9-95b4-698b6bcc5799.jpg)

**Comment by ManukMinasyan** [comment]
Hello @iamstd . What calendar version do you use?

**Comment by ManukMinasyan** [comment]
The problem has been solved successfully.
Thanks.

**Comment by iamstd** [comment]
wow. i am sorry that i see your message just now. i used your version @2.2.7. i will try your latest version later.

**Comment by iamstd** [comment]
> The problem has been solved successfully.
> Thanks.

yeah, it work very well. thanks.

**Comment by ManukMinasyan** [comment]
Thank you for your response.
