### ISSUE TITLE
Markdates not updating in v1.3.2

### ISSUE THREAD

**Issue by dieterc** [ManukMinasyan/vue-functional-calendar#2]
Since the latest update (v1.3.2) the functional calendar is not working as before.
If you update the markDate array it doesn't change this in the calendar. Only the initial dates are visible.

**Comment by ManukMinasyan** [comment]
Thank you for reporting this bug, in the next version it will be fixed. Please report other issues if you find some, all will be fixed.

**Comment by zatonsoul** [comment]
Same problem here :/

**Comment by ManukMinasyan** [comment]
> Same problem here :/

Thank you.

**Comment by ManukMinasyan** [comment]
Hello everyone. Thanks for your support. package updated to version 1.3.4.

**Comment by cqpaul** [comment]
Here the version is   "vue-functional-calendar": "^2.1.5", but the same issue, the props is reset, but the calendar is still not changing.

**Comment by cqpaul** [comment]
![image](https://user-images.githubusercontent.com/1913951/55525270-0d1b1180-56c3-11e9-813c-c3704d6ef53e.png)
![image](https://user-images.githubusercontent.com/1913951/55525282-160be300-56c3-11e9-8a6d-5ccdf5712ebb.png)
Is there any event to trigger to refresh the calendar? @ManukMinasyan

**Comment by dieterc** [comment]
I have the same issue again after updating to v2.1.2.

A temporary solution for me is adding a reference
```
<functional-calendar
    ref="calendar"
    :marked-dates="dates"></functional-calendar>
```
and do it manually like this:
```
axios.get(url)
    .then(response => {
        self.dates = response.data;
        this.$refs.calendar.fConfigs.markedDates = self.dates;
        this.$refs.calendar.markChooseDays();
    });
```

**Comment by zatonsoul** [comment]
cqpaul show me your code.

**Comment by ManukMinasyan** [comment]
For re-rendering calendar, you can update the key.
There is no API for this function.
If you have other questions, you can ask.
Thanks.

**Comment by ManukMinasyan** [comment]
#
