### ISSUE TITLE
Output result date-famater

### ISSUE THREAD

**Issue by iamstd** [ManukMinasyan/vue-functional-calendar#21]
Hi, Manuk:
      when i set date-formatter  'yyyy/mm/dd' and select date,  but the start and end of result is 'yyyy/m/d' such as '2019/5/1'  instead of '2019/05/01'.

**Comment by ManukMinasyan** [comment]
Hello @iamstd , thank you for your response.
I will look at.

**Comment by iamstd** [comment]
> Hello @iamstd , thank you for your response.
> I will look at it.
ok。Anticipation。
