### ISSUE TITLE
The limits prop is inconsistent 

### ISSUE THREAD

**Issue by cesasol** [ManukMinasyan/vue-functional-calendar#23]
I tried to setup limits on the range calendar and i saw a couple of issues:

- The limits are only respected at a month level.
- The calendar is focused on the min month rather than `currentDate`
I could not tell how this is implemented on the component in order to make a PR or any kind of suggestion

**Comment by ManukMinasyan** [comment]
I decide this on the next version.
Thank you.

**Comment by ManukMinasyan** [comment]
These problems have been fixed successfully. thanks
[https://github.com/ManukMinasyan/vue-functional-calendar/commit/611690a6e91d84b53f2d548e0872aeccbf36023f](https://github.com/ManukMinasyan/vue-functional-calendar/commit/611690a6e91d84b53f2d548e0872aeccbf36023f)
