### ISSUE TITLE
Limits props doesnt work properly

### ISSUE THREAD

**Issue by salmanorak** [ManukMinasyan/vue-functional-calendar#24]
I have set limits like below. 
`limits: {
  min: '03/06/2019', 
  max: '03/06/2020'
}
`
Have two problems
1- The months before June 2019 is not accessible,  but still dates before Jun 03 is selectable.
![image](https://user-images.githubusercontent.com/41747037/58798856-77412b80-860c-11e9-9475-46d61b8fdced.png)

2- July 2020 and Aug 2020 are still accessible,

![image](https://user-images.githubusercontent.com/41747037/58798835-67c1e280-860c-11e9-9df3-37b816ad026c.png)

Whole config is below
`            calendarConfigs : {
                sundayStart : false
                ,dateFormat:"dd/mm/yyyy"
                ,isDateRange:true
                ,isDatePicker:false    
                ,isMultiple:true 
                ,calendarsCount:2 
                ,applyStylesheet:true
                ,changeMonthFunction:false
                ,changeYearFunction:false
                ,limits: {
                    min: '03/06/2019', 
                    max: '03/06/2020'
                }
            }
`
Tried change date formats but it does not effect that i expected.
Do you have any suggestion?

**Comment by ManukMinasyan** [comment]
Hi @salmanorak , what version do you use?

**Comment by salmanorak** [comment]
Hi @ManukMinasyan,

"vue-functional-calendar": "^2.3.7",

**Comment by ManukMinasyan** [comment]
Please upgrade your version to 2.5.0
Thanks.
