### ISSUE TITLE
Template or render function not defined error

### ISSUE THREAD

**Issue by filipkrstic** [ManukMinasyan/vue-functional-calendar#26]
I have tried to use this package in Laravel project using Laravel Mix and I am getting following error:

`[Vue warn]: Failed to mount component: template or render function not defined. 
found in ---> <FunctionalCalendar> <Home> at resources/js/pages/Home.vue`

after running `npm run watch`.

There are dependencies and versions currently used in project:
```json
"axios": "^0.19",
"bootstrap": "^4.3.1",
"cross-env": "^5.1",
"font-awesome": "^4.7.0",
"laravel-mix": "^4.0.16",
"resolve-url-loader": "^2.3.1",
"sass": "^1.15.2",
"sass-loader": "^7.1.0",
"vue": "^2.6.10",
"vue-functional-calendar": "^2.5.0",
"vue-router": "^3.0.6",
"vue-template-compiler": "^2.6.10"
```

Home.vue
```html
<template>
	<main class="container">
		<FunctionalCalendar 
			v-model="calendarData"
			:sundayStart="true"
			:date-format="'dd/mm/yyyy'"
			:is-date-range="true"
			:is-date-picker="true"
		></FunctionalCalendar>
	</main>
</template>
```
```javascript
<script>
import FunctionalCalendar from 'vue-functional-calendar';

export default {
    data() {
        return {
            calendarData: {}
        };
    },
    components: {
        FunctionalCalendar,
    }
}
</script>
```

Does anyone experienced same issue on run time and what can be possible solution?

**Comment by filipkrstic** [comment]
Ohh... It works, I was doing copy/paste from README and there is:
`import FunctionalCalendar from 'vue-functional-calendar';`

But, FunctionalCalendar.vue has a name, so it should be not default but named import:
`import {FunctionalCalendar} from 'vue-functional-calendar';`

**Comment by joelxr** [comment]
I'm facing it when I try something like this:

```
const FunctionalCalendar = () => import('vue-functional-calendar')
```
