### ISSUE TITLE
多选希望开始日期和结束日期是同一天

### ISSUE THREAD

**Issue by Lee66** [ManukMinasyan/vue-functional-calendar#27]
选择日期范围的时候，希望开始日期和结束日期是同一天，好像不支持，有的插件是点击两次同一天就可以实现，希望作者可以参考

**Comment by ManukMinasyan** [comment]
Hello dear @Lee66 , Please explain in detail your problem. thanks

**Comment by Lee66** [comment]
如果is-date-range=true的情况下，我希望的选择的时间段正好是同一天，例如：startDate:2019-07-03,endDate:2019-07-03.但是发现此插件在is-date-range=true 的情况下最少需要选择2天

**Comment by ManukMinasyan** [comment]
Now I understand you, thanks for the explanation, I am doing this functionality in the next versions.
