### ISSUE TITLE
С указанием конфига падает на globalOptions

### ISSUE THREAD

**Issue by gustoase** [ManukMinasyan/vue-functional-calendar#28]
Привет, проблема обнаружилась, в случае простого импорта календаря, не используя его как плагин Vue.use(...), то падает при указании объекта конфига. Если конфигурировать через атрибуты, все хорошо.

Вот пример того, когда падает.

```
<template>
  <functional-calendar
    v-model="calendarData"
    :configs="calendarConfigs"
  />
</template>

<script>
import { FunctionalCalendar } from 'vue-functional-calendar';

export default {
  name: 'DatePicker',
  components: {
    FunctionalCalendar
  },
  data() {
    return {
      calendarData: {},
      calendarConfigs: {
        sundayStart: false,
        dateFormat: 'dd.mm.yyyy',
        isModal: true,
        isDatePicker: true,
        isAutoCloseable: true,
        isTypeable: true,
        // isDateRange: true
      }
    };
  }
};
</script>

```

```
consola.browser.js?37a1:1 error ReferenceError: globalOptions is not defined
    at eval (FunctionalCalendar.vue?1bdd:348)
    at Array.map (<anonymous>)
    at VueComponent.setConfigs (FunctionalCalendar.vue?1bdd:342)
    at VueComponent.created (FunctionalCalendar.vue?1bdd:143)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at callHook (vue.runtime.esm.js?2b0e:4213)
    at VueComponent.Vue._init (vue.runtime.esm.js?2b0e:5002)
```

Если закомментировать [этот кусок кода](https://github.com/ManukMinasyan/vue-functional-calendar/blob/4ad1c768509248452c9aa91996b3bb75d65eeb63/src/components/FunctionalCalendar.vue#L348) , все хорошо

**Comment by ManukMinasyan** [comment]
Здравствуйте @gustoase . Спасибо за вашу сообшение, я решаю эту проблему на следующих версиях.

**Comment by ManukMinasyan** [comment]
Проблема решено, [https://github.com/ManukMinasyan/vue-functional-calendar/commit/882c1d49853180667a2f0cd2cfc5e56fbac81276](https://github.com/ManukMinasyan/vue-functional-calendar/commit/882c1d49853180667a2f0cd2cfc5e56fbac81276)

Спасибо.
