### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by jaywilburn** [ManukMinasyan/vue-functional-calendar#29]
While running tests in Jest, I received this: 

DateRange.vue.js.test
`Test suite failed to run

    /Users/jaywilburn/Code/HLT/hlt-cms/node_modules/vue-functional-calendar/index.js:2
    import FunctionalCalendar from './src/components/FunctionalCalendar';
           ^^^^^^^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      13 | 
      14 | <script>
    > 15 | import { FunctionalCalendar } from 'vue-functional-calendar'
         | ^
      16 | export default {
      17 |   props: ['selectedSearchKey'],
      18 |   components: { FunctionalCalendar },

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)`

It's not able to read the import from the right path
Any ideas?

**Comment by jaywilburn** [comment]
Fixed.

**Comment by Titoine** [comment]
Could you share your fix?
Is that anything to do with **transformIgnorePatterns** ? Because I'm struggling to make it works.

**Comment by drewbaker** [comment]
Just installed this into a Nuxt project and get this same error.

**Comment by ManukMinasyan** [comment]
https://github.com/vuejs/vue-jest/issues/185#issuecomment-507727024

Please see this comment.

**Comment by drewbaker** [comment]
I'm not using Jest, just trying to use it in a Nuxt project.
