### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by DavidePapa** [ManukMinasyan/vue-functional-calendar#31]
Hi,

importing the package in the main.js file i've this error

```
Could not find a declaration file for module 'vue-functional-calendar'. '/home/xxx/app/frontend/node_modules/vue-functional-calendar/index.js' implicitly has an 'any' type.
  Try `npm install @types/vue-functional-calendar` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-functional-calendar';`ts(7016)
```

I've tried to download the types declaration file, but i receive 404 error

> Not Found - GET https://registry.npmjs.org/@types%2fvue-functional-calendar - Not found

so if i try to replace the import statement with 

`const FunctionalCalendar = require('./vue-functional-calendar')`

i receive the error

```
Module build failed: TypeError: this.getResolve is not a function
    at Object.loader (/home/xxx/app/frontend/node_modules/sass-loader/dist/index.js:52:26)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-e
b8491ac","scoped":false,"hasInlineConfig":false}!./node_modules/sass-loader/dist/cjs.js?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?ty
pe=styles&index=0!./node_modules/vue-functional-calendar/src/components/FunctionalCalendar.vue 4:14-344 13:3-17:5 14:22-352
 @ ./node_modules/vue-functional-calendar/src/components/FunctionalCalendar.vue
 @ ./node_modules/vue-functional-calendar/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

```

In the end i've tried to create a declaration file (index.d.ts, FunctionalCalendar.d.ts, vue-functional-calendar.d.ts) with

`declare module 'vue-functional-calendar'`

but even this attemps was unsuccessful. 
I'm sorry but i'm a beginner about frontend development so i restricted to some example founded on SO. I be afraid that this error depends on my envinronment

from **_package.json_**

```
 "dependencies": {
    "ag-grid-community": "^20.2.0",
    "ag-grid-vue": "^20.2.0",
    "node-sass": "^4.12.0",
    "npm": "^6.11.3",
    "sass-loader": "^8.0.0",
    "semantic-ui": "^2.4.2",
    "semantic-ui-vue": "^0.8.1",
    "vue": "^2.5.2",
    "vue-functional-calendar": "^2.6.0",
    "vue-property-decorator": "^8.2.2",
    "vue-router": "^3.1.3",
    "vue2-datepicker": "^2.12.0",
    "vuelidate": "^0.7.4",
    "vuex": "^3.1.1"
  }
```

Best regards

**Comment by ManukMinasyan** [comment]
Hi dear David. What version of your node?

**Comment by DavidePapa** [comment]
Node 8.15.1
npm 6.11.3

**Comment by ManukMinasyan** [comment]
Try node version v11.14.0

**Comment by DavidePapa** [comment]
Same error. I've a doubt: can be a problem about webpack? i've created a project via vue-cli but without typescript so i've added manually to my project.

**Comment by ManukMinasyan** [comment]
Hello dear David. Did you manage to solve the problem? If not, I can look through TeamViewer. 
Thanks.

**Comment by Titoine** [comment]
Hi,
I encountered the same problem and it's because this lib import module internally without settings the '.vue' extension. 

You have to configure webpack to allow that with something like this : 
`resolve: {
            extensions: ['*', '.js', '**.vue**', '.json'],
}`

**Comment by DavidePapa** [comment]
Hi Manuk,

i have to suspend temporarily my project. I hope during the next week i can resume that.

I thought that my problem was webpack, so meantime i have updated it to
vue-cli 4 (i'm totally newbie on JavaScript tools).

I'll let you know asap.

Best regards

Davide



>
>Il 30 gennaio 2020 12:06:08 CET, Titoine <notifications@github.com> ha
>scritto:
>>Hi,
>>I encountered the same problem and it's because this lib import module
>>internally without settings the '.vue' extension. 
>>
>>You have to configure webpack to allow that with something like this :
>
>>`resolve: {
>>            extensions: ['*', '.js', '**.vue**', '.json'],
>>}`
>>
>>-- 
>>You are receiving this because you authored the thread.
>>Reply to this email directly or view it on GitHub:
>>https://github.com/ManukMinasyan/vue-functional-calendar/issues/31#issuecomment-580202587

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.
