### ISSUE TITLE
Event when clicking on a day

### ISSUE THREAD

**Issue by teacherhogg** [ManukMinasyan/vue-functional-calendar#34]
Is it possible to have a handler function when clicking on any day?

I see somewhere an example handler saying v-on:choseDay, but this does not appear to work (BTW, probably should be v-on:chooseDay) and is not mentioned in the documentation.

Thanks!

**Comment by ManukMinasyan** [comment]
Hey @teacherhogg . 
Easily. Here` https://github.com/ManukMinasyan/vue-functional-calendar/commit/f033db1606f2a5d6c98af1278cc64e4b265fb4e7

Update the package version to 2.6.6

Thanks.
