### ISSUE TITLE
SSR compatibility

### ISSUE THREAD

**Issue by sebastianjung** [ManukMinasyan/vue-functional-calendar#36]
Hey thanks for contributing this plugin to the community.

Would it be possible to add SSR Support for like Nuxt for example?

Problem is, that its looking for a window object which is not available on SSR:

"window is not defined"

Great Plugin though!

**Comment by sebastianjung** [comment]
Catching those 'window' Objects with` if (typeof window !== 'undefined')` already helped for me though i am not sure if that is the right way to do it.

![image](https://user-images.githubusercontent.com/17472892/69038700-a137b000-09ea-11ea-969d-01f44ee53c90.png)

![image](https://user-images.githubusercontent.com/17472892/69040431-13f65a80-09ee-11ea-88c0-046a9bbba116.png)

**Comment by ManukMinasyan** [comment]
Hey @sebastianjung.
Your solution is correct.
Thanks

**Comment by TitanFighter** [comment]
Simple way:

```
  components: {
    ...
    FunctionalCalendar: () => process.client ? import('vue-functional-calendar/src/components/FunctionalCalendar.vue') : null,
    ...
  },
```
