### ISSUE TITLE
Date Picker with date range bug

### ISSUE THREAD

**Issue by meiektaus8** [ManukMinasyan/vue-functional-calendar#39]
A user opens the Date Picker (with date range) for the first time and select Start Date and End Date. Date range between Start and End date is highlighted.
Screenshot [here](https://drive.google.com/file/d/12x-ne34Elz70NLsH0fsFUfp5IuE7J-ki/view?usp=sharing)
Then the user opens the Date Picker again.
Screenshot [here](https://drive.google.com/file/d/1BvLeEqSUC7QODFB0re4MvfoXeZDM4K2T/view?usp=sharing)

**Actual result:**
Date range between Start and End date is not highlighted. CSS class `.vfc-marked.vfc-hover` that make date range highlighted is absent.

**Expected result:** 
Date range between Start and End date displays as highlighted and CSS class `.vfc-marked.vfc-hover` presents.

**Comment by ignasga** [comment]
How did you change the style (colours, fonts) of the calendar? I really need this but I didn't find any documented way to configure the looks.

**Comment by meiektaus8** [comment]
@ignasga We changed style using CSS by overriding the default style.

**Comment by LaurentiaW** [comment]
Same issue
![vue-functional-calendar-no-marked dates](https://user-images.githubusercontent.com/22709212/70543480-bbd4f300-1b6a-11ea-830f-2fec735ba1dd.PNG)
.vfc-marked class absent between the .vfc-base-start and .vfc-base-end divs

**Comment by ManukMinasyan** [comment]
Hey @meiektaus8, @LaurentiaW 
Please take a look this example https://y3jnxov469.codesandbox.io/ ,
and paste your code here. Thanks.

**Comment by LaurentiaW** [comment]
Hey @ManukMinasyan 
So I have a component Calendar 

<template>
    <div id="calendar">
        <FunctionalCalendar :sunday-start='true'
                            :hidden-elements="['leftAndRightDays']"
                            :marked-dates='markedDates'
                            :limits="{min: value , max: ''}"
                            ref="Calendar"
                            :isDatePicker="true"
                            :is-date-range='isDateRange'
                            :is-multiple='true'
                            :calendars-count='monthviews'
                            v-model="userSelectedDates"
                            @choseDay="choseDay">
        </FunctionalCalendar>
        
    </div>
</template>

**Comment by LaurentiaW** [comment]
Hey @ManukMinasyan 

So I created a Calendar component based on your plugin

<template>
    <div id="calendar">
        <FunctionalCalendar :sunday-start='true'
                            :hidden-elements="['leftAndRightDays']"
                            :marked-dates='markedDates'
                            :limits="{min: value , max: ''}"
                            ref="Calendar"
                            :isDatePicker="true"
                            :is-date-range='isDateRange'
                            :is-multiple='true'
                            :calendars-count='monthviews'
                            v-model="userSelectedDates"
                            @choseDay="choseDay">
        </FunctionalCalendar>
    </div>
</template>

<script lang="ts">
    import Vue from 'vue';
    import { State, Mutation, Action, Getter } from 'vuex-class';
    import { Component, Emit, Prop, Watch } from 'vue-property-decorator';
    import { ProjectStateGetters, ProjectStateActions } from '../../States';
    import { CategoryData } from '../../Types';
    import { FunctionalCalendar } from 'vue-functional-calendar';

    @Component({
        components: { FunctionalCalendar },
        name: "Calendar"
    })
    export default class extends Vue {
        
        $refs!: {
            Calendar: Vue
        }
        
        userSelectedDates: object = {}

        @Prop()
        dates!: Date[];

        @Prop()
        markedDates: object = [];

        @Prop({ default: false })
        isDateRange!: boolean;
        
        @Prop({ default: 1 })
        monthviews!: number;

        value: string = (new Date().toJSON().slice(0,10).replace(/-/g,'/').split('/')).reverse().join('/')

        constructor() {
            super();
            this.markedDateFormatter();
        }

        markedDateFormatter() {
            for (var i = 0; i < this.dates.length; i++) {
                this.markedDates[i] = this.formatDate(this.dates[i]);
            }
        }

        formatDate(date: Date) : string {
            return date.getDate() + '/' + (date.getMonth() + 1)  + '/' + date.getFullYear();
        }

      

        choseDay(day) {
            for (var i = 0; i < this.dates.length; i++) {
                if (day.date == this.formatDate(this.dates[i])) {
                    //@ts-ignore
                    this.$parent.choseDay(this.dates[i]);
                }
            }
            this.$emit('choseDay', this.userSelectedDates);
        }
             
        callFunction() {
            const currentDateWithFormat = new Date().toJSON().slice(0,10).replace(/-/g,'/');
            console.log(currentDateWithFormat);

            const dateFormat = (currentDateWithFormat.split('/')).reverse().join('/');
            console.log(dateFormat);
            this.value = dateFormat;
            }
     }
</script>

And then I use this component in another component

<Calendar ref="datepicker"
                          :dates="eventDates"
                          :isDateRange="true"
                          :monthviews="isMobile? 1 : 2"
                          @choseDay="selectedDates" />


//for the selected days
      selectedDates(data) {
            console.log(data);
        }


So as per my first comment the calendar renders on the page everything renders as expected the only thing that I don't understand is that the days between the .vfc-base-start & .vfc-base-end divs are not marked as per your example 

![image](https://user-images.githubusercontent.com/22709212/70711068-e9dc4380-1ce0-11ea-9314-c8c9341d7c12.png)
As you can see on the screenshot if you have a starting and an end date selected your would expect the in between date to have the class .vfc-marked as per your example. 
Do you have any suggestions? 

Thanks!

**Comment by LaurentiaW** [comment]
Missing the template 
<template>
    <div id="calendar">
        <FunctionalCalendar :sunday-start='true'
                            :hidden-elements="['leftAndRightDays']"
                            :marked-dates='markedDates'
                            :limits="{min: value , max: ''}"
                            ref="Calendar"
                            :isDatePicker="true"
                            :is-date-range='isDateRange'
                            :is-multiple='true'
                            :calendars-count='monthviews'
                            v-model="userSelectedDates"
                            @choseDay="choseDay">
        </FunctionalCalendar>
    </div>
</template>

**Comment by meiektaus8** [comment]
@ManukMinasyan Please, update your code on npmjs.com. Seems that you fixed the issue, but didn't publish.

**Comment by ManukMinasyan** [comment]
> @ManukMinasyan Please, update your code on npmjs.com. Seems that you fixed the issue, but didn't publish.

Please see you package.json. Code updated on npm. Thanks.

**Comment by SpinyMan** [comment]
@ManukMinasyan now all days even not marked have next classes list: `vfc-span-day vfc-hover`
:(
