### ISSUE TITLE
BUG with calendar property markedDates: []

### ISSUE THREAD

**Issue by ignasga** [ManukMinasyan/vue-functional-calendar#40]
Hi!
In my case I assign values to markedDates: [] array, then rerender calendar, so it starts to show these days with blue circle, so they are marked.

Let's assume I assigned this value to the markedDates array:
[
  "2019-12-6",
  "2019-12-9",
  "2019-12-10",
  "2019-12-11",
  "2019-12-12",
  "2020-01-1"
]

Now every day that is specified in this current month (12th month currently) is marked.
But if I click arrow to go to next month, then 2020-01-01 is supposed to be marked, but it isn't.
I trid to rerender calendar, when nextMonth callback was called, but then calendar resets to current month, and problem persists.

Please give any suggestions to workaround or fix this :)

**Comment by ManukMinasyan** [comment]
Hello. You need to use "2020-1-1" and not "2020-01-1". Thanks
