### ISSUE TITLE
functional-calendar parent with v-show causes vfc-main-container height:0

### ISSUE THREAD

**Issue by deivthings** [ManukMinasyan/vue-functional-calendar#43]
If funcional-calendar is wrapped by a element that uses v-show (like a modal or dropdown...) on mounted hook calculate the height of the container to 0.

thanks for your effort

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
