### ISSUE TITLE
Changed in markedDate doesn't update the calendar

### ISSUE THREAD

**Issue by Titoine** [ManukMinasyan/vue-functional-calendar#48]
Hi,

as you can see there : https://codesandbox.io/s/markeddate-doesnt-update-yfiwt
When we add a marked date with the button 'add date' the calendar doesn't update.
I have to trigger something to make it refresh like calling ChooseDate.

Am I missing something? 
I'm new to vue and the reactivity system isn't something I'm mastering.

**Comment by daaner** [comment]
Faced a similar problem. Alas, markedDates are not reactive
although dateDisabled works just fine

**Comment by daaner** [comment]
It is solved only by re-render the component. I think it will suit me perfectly
```
: key="index"
```

**Comment by ManukMinasyan** [comment]
Hey guys. Thank you for your feedback, this problem was resolved in version 2.8.0.

Thanks
