### ISSUE TITLE
Disabled dates are clickable

### ISSUE THREAD

**Issue by sp0ken** [ManukMinasyan/vue-functional-calendar#52]
When using `:is-date-picker="true"` and `:disabledDates="['beforeToday']"` dates before today are disabled but still clickable and selectable.

Check here to see it in action: https://codesandbox.io/s/vuejs-functional-calendar-component-6ript?fontsize=14&hidenavigation=1&theme=dark

**Comment by ManukMinasyan** [comment]
@sp0ken Thank you for your feedback.
This problem solved in version v2.8.61

**Comment by lucapu88** [comment]
i have the same problem on the latest version (2.8.88)

**Comment by lucapu88** [comment]
@ManukMinasyan  i have the same problem on the latest version (2.8.88)
