### ISSUE TITLE
Selected dates range by default

### ISSUE THREAD

**Issue by Seaclick** [ManukMinasyan/vue-functional-calendar#54]
Hello @ManukMinasyan 

**Thanks for this awesome package, it works like a charm** but I encounter a little issue.
I am trying to select date range on page load when URL has _checkin_ and _checkout_ parameters.
I have seen that it was possible [here](https://y3jnxov469.csb.app/) with marked-date-range prop, but i am surely missing something.

`(vue-functional-calendar V. 2.8.61)`

Here is how I proceed :

First of all, the URL:
![image](https://user-images.githubusercontent.com/20319629/76945497-e3262380-6902-11ea-88b3-9301c2877705.png)

As you can see there is the both datas: checkin and checkout. I get this datas thanks to a JS helper I created. I tested it of course in my console and it's working.

The FunctionalCalendar component is implemented like that:
![image](https://user-images.githubusercontent.com/20319629/76945240-87f43100-6902-11ea-90a3-f91f9af37e9e.png)

When the component is created I use the helper to get the date range and call a method named "buildDateRange()".
![image](https://user-images.githubusercontent.com/20319629/76944798-ec62c080-6901-11ea-993f-e87c7596a6f7.png)

Thanks this method I update the vue model with this:
![image](https://user-images.githubusercontent.com/20319629/76945833-65164c80-6903-11ea-8285-9ea71dc534cf.png)

In the Vue console we can see that the model is updated
![image](https://user-images.githubusercontent.com/20319629/76946041-b7f00400-6903-11ea-8144-1840095d4c99.png)

Because It was not working, I have also try with the marked-date-range prop and the markedDateRange object:
![image](https://user-images.githubusercontent.com/20319629/76946338-2b921100-6904-11ea-8ff2-84d3a693e86a.png)

And put the dates range in the marked-date-range prop int he "buildDateRange()" method like that:
![image](https://user-images.githubusercontent.com/20319629/76946572-84fa4000-6904-11ea-9780-3321f9f7c2cf.png)

As you can see, the datas are inserted in the markedDateRange on page load:
![image](https://user-images.githubusercontent.com/20319629/76946675-aeb36700-6904-11ea-9c17-16faf0cbdc2c.png)

Unfortunately, it's still not working. :/

Am I missing something?

**Comment by ManukMinasyan** [comment]
Hello @Seaclick .
Thank you for your message.
Please follow this source: https://codesandbox.io/s/vuejs-functional-calendar-component-5j096
Live demo: https://5j096.csb.app/?checkin=2020-3-20&checkout=2020-3-28

**Comment by Seaclick** [comment]
@ManukMinasyan Thanks for your answer, but it still not working.

I missed to tell you that the component is in a div with a v-show and is not showed on page load. Maybe it's because of that.

Anyway, thanks a lot for your help.

Regards,
