### ISSUE TITLE
minSelDays option

### ISSUE THREAD

**Issue by SpinyMan** [ManukMinasyan/vue-functional-calendar#57]
Property `minSelDays` exists but does nothing. When you plan to implement it?

**Comment by ManukMinasyan** [comment]
This functionality only works correctly for date ranges.
For this, I created a task.
https://github.com/ManukMinasyan/vue-functional-calendar/projects/1#card-35470519

Thanks.

**Comment by SpinyMan** [comment]
> This functionality only works correctly for date ranges.

Could you please provide an example, cause mine doesn't work at all.

**Comment by ManukMinasyan** [comment]
> > This functionality only works correctly for date ranges.
> 
> Could you please provide an example, cause mine doesn't work at all.

Minimum and Maximum selected days
https://y3jnxov469.codesandbox.io/

```
<functional-calendar  :is-date-range='true'  :min-sel-days='3'
        :max-sel-days='6'></functional-calendar>
```
