### ISSUE TITLE
 how to get the value of only one day

### ISSUE THREAD

**Issue by fingunt** [ManukMinasyan/vue-functional-calendar#58]
how to get the value of only one day?

**Comment by ManukMinasyan** [comment]
Hi @fingunt.
To be honest, I did not understand the question

**Comment by fingunt** [comment]
sorry, I'm using it as a datepicker for only one day, but it's not returning the selected date

**Comment by ManukMinasyan** [comment]
You can get the date with ref. Or you can use the v-model
