### ISSUE TITLE
not support in IE11.

### ISSUE THREAD

**Issue by wangyansong** [ManukMinasyan/vue-functional-calendar#60]
error: SCRIPT1002

**Comment by Titoine** [comment]
any news on this ?

**Comment by CBillings92** [comment]
I'm receiving this error as well. The error in IE11 is `SCRIPT1002: Syntax error`. The error seems to be pointing to the following code in helpCalendar.js

![image](https://user-images.githubusercontent.com/6538311/82851077-79eaff80-9eb3-11ea-9b36-cdd1d79725a2.png)

The version we're using is `vue-functional-calendar: ^2.8.0` (2.8.83 specifically) - hopefully this info is helpful!

**Comment by wangyansong** [comment]
edit file webpack.base.conf.js maybe useful.
    {
        test: /\.js$/,
        loader: 'babel-loader?cacheDirectory',
        include: [resolve('src'), resolve('test'), resolve('/node_modules/vue-functional-calendar')]
      },
![calendar](https://user-images.githubusercontent.com/27467399/82965529-fa684800-9ffa-11ea-936b-2a5f9fb291d3.jpg)

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
