### ISSUE TITLE
How to show the initial date

### ISSUE THREAD

**Issue by stuta** [ManukMinasyan/vue-functional-calendar#72]
In mounted() method I use `this.$refs.Calendar.ChooseDate('15.04.2020')` to set date, but still initial display is only placeholder `dd.mm.yyyy`. When I click to field it shows datepicker and after the pick, I see the chosen date in the input field.

In this example, the end date has been picked but the start date shows only the placeholder.

![Screenshot 2020-05-04 at 20 47 25](https://user-images.githubusercontent.com/1422999/80996543-a37eb100-8e48-11ea-8f58-6ec6d2f93733.png)

How can I show the initial date in the input field?

This is my config:

```js
calendarData: {},
calendarConfig: {
	showWeekNumbers: true,
	changeMonthFunction: true,
	changeYearFunction: true,
	changeYearStep: 1,
	calendarsCount: 1,
	isModal: true,
	isAutoCloseable: true,
	isDatePicker: true,
	isMultiple: true,
	isMultipleDatePicker: true,
	isDateRange: false,
	isTypeable: true,
	transition: true,
	sundayStart: false,
	placeholder: false,
	dateFormat: 'dd.mm.yyyy'
}
```

**Comment by stuta** [comment]
I found a simple fix:

https://github.com/ManukMinasyan/vue-functional-calendar/pull/59#issuecomment-623627471

I wish we could use v-model so there would be no need for mounted() and this.$refs that is not compatible with Vue 3. The v-model is the source of data in all other components.

it could be like this:
```js
calendarData: {
  date: '01.04.2020'
}
```

**Comment by ManukMinasyan** [comment]
Hello @stuta, you can do this with slots.

**Comment by stuta** [comment]
How?

**Comment by ManukMinasyan** [comment]
```
<Calendar class="calendar" :configs="configs">
	<template v-slot:dateRangeInputs="props">
          <label>
            <i class="d-icon icon-datepicker"/>
            <input
              v-model="props.startDate"
              type="text"
              placeholder="Check in"
              value="date1"
              readonly
            >
          </label>
          <label>
            <i class="d-icon icon-datepicker"/>
            <input
              v-model="props.endDate"
              type="text"
              placeholder="Check Out"
              value="date2"
              readonly
            >
          </label>
        </template>
		
  </Calendar>
```

**Comment by stuta** [comment]
I don't use date range, I have only one input. I had 2 different inputs in my example.

Where are the slots documented?

**Comment by ManukMinasyan** [comment]
Documentation for that is currently unavailable.

```
<Calendar class="calendar" :configs="configs">
<template v-slot:datePickerInput="props">
         <input class="vfc-single-input" type="text" title="Date"
                       v-model="props.selectedDate">
</template>
</Calendar>
```

**Comment by TitanFighter** [comment]
Few notes:
1. Just for those who is not good with slots -> how to get values from "props"? -> add `v-model="calendarData"` (with the same var in data() ) to `<Calendar class="calendar" :configs="configs">`, so it must be  `<Calendar v-model="calendarData" class="calendar" :configs="configs">`
2. The example also shows how to change placeholder (actually two placeholders) for range selection in modal mode.
