### ISSUE TITLE
 Could not find a declaration file for module 'vue-functional-calendar'.

### ISSUE THREAD

**Issue by selvievski** [ManukMinasyan/vue-functional-calendar#76]
I'm using the functional calendar in vuejs application in combination with typescript. I'm getting this error "Could not find a declaration file for module 'vue-functional-calendar'."
I've tried to add custom .d.ts file but still there is an error from eslint and build fails.
![image](https://user-images.githubusercontent.com/33196897/81437222-164e9b80-916b-11ea-9a52-e4b5fcb86ecd.png)
![image](https://user-images.githubusercontent.com/33196897/81437403-66c5f900-916b-11ea-8615-e38c157e29aa.png)

**Comment by andynoir** [comment]
@selvievski

Try it like this:

1) Create a `vue-functional-calendar.d.ts` file and put it somewhere in your project
2) Declare your typing in the file, for eg.

```
declare module 'vue-functional-calendar' {
    import Vue from 'vue';

    class FunctionalCalendar extends Vue {
      // your types here
    }
    export = FunctionalCalendar;
}
```

3) Then go to your `tsconfig.json` file and add `typeRoots`:

```
{
  "compilerOptions": {
    "typeRoots": [
      "./node_modules/@types",
      "./src/types/vue-functional-calendar.d.ts",
    ]
  },
}
```

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
