### ISSUE TITLE
Limits  prop doesn't work

### ISSUE THREAD

**Issue by devkarinlim** [ManukMinasyan/vue-functional-calendar#79]
Hi, i set the limits prop, but it doesn't work. Can you help me?
:limits="{min: '16/05/2020', max: '24/05/2020'}"

![image](https://user-images.githubusercontent.com/65513703/82161615-85916180-98c8-11ea-8d0f-79d96524ffc7.png)

**Comment by ManukMinasyan** [comment]
Hi, You need to write dates without zero.
:limits="{min: '16/5/2020', max: '24/5/2020'}"
