### ISSUE TITLE
Month buttons are behaving inversely.

### ISSUE THREAD

**Issue by adititare-tudip** [ManukMinasyan/vue-functional-calendar#99]
When trying to refresh the calendar, the whole calendar gets refreshed but the next and previous buttons for the month are behaving inversely. previous month button gets enable and next month's button gets disabled.

![month_buttons_behaving_inversely](https://user-images.githubusercontent.com/44598297/88663385-25edd880-d0f9-11ea-85c3-d4382f572946.png)

**Comment by ManukMinasyan** [comment]
Hello. Thanks for your feedback. Now I don't have time to deal with the calendar. Please create pull requests, I will appreciate it, it will be useful for the community.
